---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    entando.org/entando-resource-namespace: "my-namespace"
    TestResource: "my-app"
    entando.org/entando-resource-kind: "TestResource"
  name: "my-app-76765571"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "test.org/v1"
    kind: "TestResource"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "c865c538-0e27-42fb-8015-58e2f5638063"
action: "FAILED"
count: 1
firstTimestamp: "2021-11-10T11:13:29Z"
involvedObject:
  apiVersion: "test.org/v1"
  kind: "TestResource"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "7755708"
  uid: "c865c538-0e27-42fb-8015-58e2f5638063"
lastTimestamp: "2021-11-10T11:13:29Z"
message: "The deployment of TestResource my-namespace/my-app failed due to Database\
  \ preparation failed. Please inspect the logs of the pod my-namespace/my-app-dbprep-1985.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "test-controller-pod"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-ource-controller"
type: "Error"
